DELETE FROM Espectaculo;
INSERT INTO Espectaculo (Titulo, Tipo, Productor) VALUES
('El Rey León', 'Musical', 'Disney Theatrical Productions'),
('El Fantasma de la Ópera', 'Musical', 'Really Useful Group'),
('Wicked', 'Musical', 'Marc Platt'),
('Hamilton', 'Musical', 'Lin-Manuel Miranda'),
('Romeo y Julieta', 'Teatro', 'Shakespeare Productions'),
('La Bella y la Bestia', 'Musical', 'Disney Theatrical Productions'),
('Chicago', 'Musical', 'Barry and Fran Weissler'),
('Les Misérables', 'Musical', 'Cameron Mackintosh'),
('Cats', 'Musical', 'The Really Useful Group'),
('Mamma Mia!', 'Musical', 'Benny Andersson & Björn Ulvaeus'),
('El Guardaespaldas', 'Musical', 'Michael Harrison'),
('El Rey Lear', 'Teatro', 'Royal Shakespeare Company'),
('Sweeney Todd', 'Musical', 'Stephen Sondheim'),
('El Fantasma de Canterville', 'Teatro', 'Teatro de la Ciudad'),
('Annie', 'Musical', 'Martin Charnin'),
('El Jorobado de Notre Dame', 'Musical', 'Disney Theatrical Productions'),
('Don Juan Tenorio', 'Teatro', 'Compañía Nacional de Teatro'),
('Billy Elliot', 'Musical', 'Universal Pictures Stage Productions'),
('El Lago de los Cisnes', 'Ballet', 'Teatro Bolshói'),
('La Traviata', 'Ópera', 'Metropolitan Opera'),
('Hairspray', 'Musical', 'Margo Lion'),
('Jersey Boys', 'Musical', 'Dodger Theatricals'),
('Cabaret', 'Musical', 'Harold Prince'),
('El Mago de Oz', 'Musical', 'Andrew Lloyd Webber'),
('La Flauta Mágica', 'Ópera', 'Wiener Staatsoper'),
('Mary Poppins', 'Musical', 'Cameron Mackintosh'),
('Porgy and Bess', 'Ópera', 'Gershwin Estate'),
('El Cascanueces', 'Ballet', 'Teatro Mariinsky'),
('El Hombre de la Mancha', 'Musical', 'Albert Marre'),
('La Sirenita', 'Musical', 'Disney Theatrical Productions'),
('La La Land', 'Película', 'Summit Entertainment'),
('Bohemian Rhapsody', 'Película', '20th Century Fox'),
('El Padrino', 'Película', 'Paramount Pictures'),
('Titanic', 'Película', '20th Century Studios'),
('Avatar', 'Película', '20th Century Studios'),
('Jurassic Park', 'Película', 'Universal Pictures'),
('Star Wars: Episodio IV - Una nueva esperanza', 'Película', 'Lucasfilm'),
('Harry Potter y la piedra filosofal', 'Película', 'Warner Bros. Pictures'),
('Campeones', 'Pelicula', 'Morena Films'),
('El Señor de los Anillos: La Comunidad del Anillo', 'Película', 'New Line Cinema'),
('Concierto de Coldplay', 'Concierto', 'Live Nation'),
('Concierto de U2', 'Concierto', 'Live Nation'),
('Concierto de Metallica', 'Concierto', 'Live Nation'),
('Concierto de Extremoduro', 'Concierto', 'Warner Music Spain'),
('Concierto de Vetusta Morla', 'Concierto', 'Sonora S.A.'),
('Concierto de Amaral', 'Concierto', 'Gato Negro Producciones'),
('Concierto de El Barrio', 'Concierto', 'Riff Producciones'),
('Concierto de Rosalía', 'Concierto', 'Sony Music Entertainment'),
('Concierto de Love of Lesbian', 'Concierto', 'Warner Music Spain'),
('Concierto de La Oreja de Van Gogh', 'Concierto', 'Sony Music Entertainment'),
('Celta de Vigo vs Athletic Club', 'Partido de Futbol', 'La Liga'),
('Celta de Vigo vs Atlético de Madrid', 'Partido de Futbol', 'La Liga'),
('Celta de Vigo vs Levante UD', 'Partido de Futbol', 'La Liga'),
('Celta de Vigo vs Real Madrid', 'Partido de Futbol', 'La Liga'),
('Celta de Vigo vs Valencia CF', 'Partido de Futbol', 'La Liga'),
('FC Barcelona vs Celta de Vigo', 'Partido de Futbol', 'La Liga'),
('Getafe CF vs Celta de Vigo', 'Partido de Futbol', 'La Liga'),
('Real Sociedad vs Celta de Vigo', 'Partido de Futbol', 'La Liga'),
('Sevilla FC vs Celta de Vigo', 'Partido de Futbol', 'La Liga'),
('Villarreal CF vs Celta de Vigo', 'Partido de Futbol', 'La Liga');

